server:
  port: 9000

spring:
  application:
    name: shrek-auth
  hikari:
        connection-test-query: SELECT 1
        minimum-idle: 1
        maximum-pool-size: 5
        pool-name: dbcp1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/auth?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
  redis:
    host: 127.0.0.1
    password:
    port: 6379

security:
  oauth2:
    client:
      client-id: pig
      client-secret: pig
      user-authorization-uri: http://localhost:3000/oauth/authorize
      access-token-uri: http://localhost:3000/oauth/token
      scope: server
    resource:
      loadBalanced: true
      token-info-uri: http://localhost:3000/oauth/check_token

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug